{% set name = "mysql-connector-odbc" %}
{% set version = "8.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dev.mysql.com/get/Downloads/Connector-ODBC/{{ name }}-{{ version }}-src.tar.gz
  sha256: 423c04faba403e9e4e319e878781be612b6c575d8b062d6db60b36e804477517

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - unixodbc
    - mysql-devel {{ version }}

test:
  commands:
    - test -f "$PREFIX/lib/libmyodbc8w${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libmyodbc8a${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/bin/myodbc-installer"         # [unix]

about:
  home: https://dev.mysql.com/doc/connector-odbc/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: MySQL Connector/ODBC, the ODBC interface for communicating with MySQL servers.

extra:
  recipe-maintainers:
    - xhochy
