{% set name = "mysql-connector-odbc" %}
{% set version = "9.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dev.mysql.com/get/Downloads/Connector-ODBC/{{ name }}-{{ version }}-src.tar.gz
  sha256: 42df023046c343a647c840750697e142b3ca633a4c03fc5c6b22ad5b54340471
  patches:
    - patches/0001-Add-missing-includes.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - zlib                       # [target_platform != build_platform]
    - unixodbc                   # [target_platform != build_platform]
    - mysql-devel {{ version }}  # [target_platform != build_platform]
  host:
    - zlib
    - unixodbc
    - mysql-devel {{ version }}

test:
  commands:
    - test -f "$PREFIX/lib/libmyodbc8w${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/lib/libmyodbc8a${SHLIB_EXT}"  # [unix]
    - test -f "$PREFIX/bin/myodbc-installer"         # [unix]

about:
  home: https://dev.mysql.com/doc/connector-odbc/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: MySQL Connector/ODBC, the ODBC interface for communicating with MySQL servers.

extra:
  recipe-maintainers:
    - jonashaag
    - xhochy
