schema_version: 1

context:
  name: mysql-connector-odbc
  version: "9.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mysql/mysql-connector-odbc/archive/refs/tags/${{ version }}.tar.gz
  sha256: 9b2a57b32e952b012363144a96c83aac40c07c889ccf4a2e9c1db1eb90572008
  patches:
    - if: osx
      then: 0001-Added-a-std-char_traits-unsigned-short-specializatio.patch

build:
  number: 1
  skip: win

requirements:
  build:
    - cmake
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: target_platform != build_platform
      then:
        - zlib
        - unixodbc
        - mysql-devel ${{ version }}.*
  host:
    - zlib
    - unixodbc
    - mysql-devel ${{ version }}.*

tests:
  - script:
      - if: unix
        then:
          - "test -f \"$PREFIX/lib/libmyodbc9w${SHLIB_EXT}\""
          - "test -f \"$PREFIX/lib/libmyodbc9a${SHLIB_EXT}\""
          - "test -f \"$PREFIX/bin/myodbc-installer\""
about:
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_file: LICENSE.txt
  summary: MySQL Connector/ODBC, the ODBC interface for communicating with MySQL servers.
  homepage: https://dev.mysql.com/doc/connector-odbc/en/

extra:
  recipe-maintainers:
    - jonashaag
    - xhochy
