schema_version: 1

context:
  name: mysql-connector-odbc
  version: 9.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://dev.mysql.com/get/Downloads/Connector-ODBC/${{ name }}-${{ version }}-src.tar.gz
  sha256: 42df023046c343a647c840750697e142b3ca633a4c03fc5c6b22ad5b54340471
  patches:
    - patches/0001-Add-missing-includes.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - cmake
    - ninja
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: target_platform != build_platform
      then: zlib
    - if: target_platform != build_platform
      then: unixodbc
    - if: target_platform != build_platform or target_platform != build_platform
      then: mysql-devel 9.3.0.*
  host:
    - zlib
    - unixodbc
    - mysql-devel 9.3.0.*

tests:
  - script:
      - if: unix
        then: "test -f \"$PREFIX/lib/libmyodbc8w${SHLIB_EXT}\""
      - if: unix
        then: "test -f \"$PREFIX/lib/libmyodbc8a${SHLIB_EXT}\""
      - if: unix
        then: "test -f \"$PREFIX/bin/myodbc-installer\""

about:
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_file: LICENSE.txt
  summary: MySQL Connector/ODBC, the ODBC interface for communicating with MySQL servers.
  homepage: https://dev.mysql.com/doc/connector-odbc/en/

extra:
  recipe-maintainers:
    - jonashaag
    - xhochy
