conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
bot: {check_solvable: true}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
